version: '3'

services:
  app:
    image: lastfastapi
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL ="postgresql://ut0ztscbg7bwh430opt8:TzulfsMyKjm0U8kuXK0wV9lrl523h8@b2hubzeul8olahp6fwol-postgresql.services.clever-cloud.com:5432/b2hubzeul8olahp6fwol"


  db:
    image: postgres
    restart: always
    environment:
      - DATABASE_URL ="postgresql://ut0ztscbg7bwh430opt8:TzulfsMyKjm0U8kuXK0wV9lrl523h8@b2hubzeul8olahp6fwol-postgresql.services.clever-cloud.com:5432/b2hubzeul8olahp6fwol"

    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: